name: Build and Deploy to AWS S3
on:
  push:
    branches:
      - master  # Trigger on PRs targeting 'master' branch
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for OIDC
      contents: read   # Required to fetch repo contents
    steps:
      # Step 0: Cache node_modules and Vite cache
      - name: Cache node_modules and Vite cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            **/.vite
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci --include=dev

      - name: Echo before build
        run: echo "Starting build step..."

      # Step 4: Build the project
      - name: Build package
        run: NODE_OPTIONS="--max_old_space_size=4096" npm run build

      # Step 5: Configure AWS credentials via OIDC
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_S3_ARN }}
          aws-region: ap-southeast-2
          mask-aws-account-id: true

      # Step 6: Upload to S3
      - name: Upload to S3
        run: |
          aws s3 cp ./dist s3://universal-login-sample-app/ --recursive